---
- name: CTF VM provisioning
  hosts: all

  vars_prompt:
    # - name: hostname
    #   prompt: "Hostname for this machine"

    # - name: user_password
    #   prompt: "User password for this machine"
    #   private: yes
    #   encrypt: "sha512_crypt"
    #   confirm: yes

    # - name: password
    #   prompt: "Root password for this machine"
    #   private: yes
    #   encrypt: "sha512_crypt"
    #   confirm: yes

  tasks:
    - name: Get current username
      local_action: command whoami
      register: username

    # - name: Change user password
    #   become: yes
    #   user:
    #     name: "{{ username.stdout }}"
    #     password: "{{ user_password }}"

    # - name: Change root password
    #   become: yes
    #   user:
    #     name: root
    #     password: "{{ password }}"

    # - name: Disable automatic repositories update
    #   become: yes
    #   replace:
    #     path: /etc/apt/apt.conf.d/20auto-upgrades
    #     regexp: 'APT::Periodic::Update-Package-Lists "1";'
    #     replace: 'APT::Periodic::Update-Package-Lists "0";'

    # - name: Disable automatic software update
    #   become: yes
    #   replace:
    #     path: /etc/apt/apt.conf.d/20auto-upgrades
    #     regexp: 'APT::Periodic::Unattended-Upgrade "1";'
    #     replace: 'APT::Periodic::Unattended-Upgrade "0";'

    - name: Wait for any possibly running unattended upgrade to finish
      become: yes
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Fix for exim4
      become: yes
      shell: echo 'kali' > /etc/mailname

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        # Base install
        - ack
        - apache2
        - arping
        - chromium
        - cloc
        - curl
        - dhex
        - entr
        - fd-find
        - flake8
        - fzf
        - git
        - golang
        - htop
        - imagemagick
        - libapache2-mod-php
        - ncdu
        - neovim
        - nodejs
        - npm
        - openvpn
        - pastebinit
        - php
        - python-pip
        - python3-pip
        - ranger
        - ruby
        - tmux
        - tree
        - wget
        - xclip
        - yarn
        - zsh

        # Docker
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common

        # Binary exploitation
        - checksec

        # Bruteforce
        - cewl
        - crackmapexec
        - crunch
        - fcrackzip
        - hydra
        - john
        - samdump2
        - wordlists

        # Exploiting
        - exploitdb
        - metasploit-framework

        # Forensics
        - audacity
        - binwalk
        - exiftool
        - foremost
        - libguestfs-tools
        - pngcheck
        - qsstv
        - sonic-visualiser
        - steghide
        - volatility
        - zbar-tools

        # Fuzzing and discovery
        - dirbuster
        - gobuster
        - sublist3r
        - wfuzz

        # Information gathering
        - dnsutils
        - whois

        # Web tools
        - amass
        - burpsuite
        - eyewitness
        - httprint
        - sqlmap
        - whatweb

        # Miscellaneous
        - gridsite-clients      # url encoding/decoding
        - hexedit
        - jq
        - rlwrap

        # Networking
        - aircrack-ng
        - arping
        - dnschef
        - dsniff
        - fern-wifi-cracker
        - hping3
        - ncat
        - netcat
        - nmap
        - sbd
        - tor
        - tshark
        - wireshark

        # Reversing
        - dex2jar
        - gdb
        - ltrace
        - radare2
        - strace

        # Samba
        - cifs-utils
        - smbclient
        - smbmap

        # Vulnerability analysis
        - golismero
        - lynis
        - nikto

        # Dependencies
        - libzip-dev            # radare decompiler plugin
        # - python-argcomplete    # golismero
        - python-dnspython

    # Docker installation
    - name: Add Docker's GPG key
      become: yes
      args:
        warn: false
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker's repository
      become: yes
      shell: echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-compose

    - name: Enable Docker
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      become: yes
      shell: usermod -a -G docker {{ username.stdout }}

    # Configure services for metasploit
    - name: Enable apache
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Enable postgresql
      become: yes
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Initialize msfdb
      become: yes
      shell: "{{ item }}"
      with_items:
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    # Linux stuff
    - name: Set zsh shell
      become: yes
      user:
        name: "{{ username.stdout }}"
        shell: /bin/zsh

    - name: Change XDG directories
      shell: "{{ item }}"
      with_items:
        - xdg-user-dirs-update --set DESKTOP $HOME
        - xdg-user-dirs-update --set DOCUMENTS $HOME
        - xdg-user-dirs-update --set DOWNLOAD $HOME
        - xdg-user-dirs-update --set MUSIC $HOME
        - xdg-user-dirs-update --set PICTURES $HOME
        - xdg-user-dirs-update --set PUBLICSHARE $HOME
        - xdg-user-dirs-update --set TEMPLATES $HOME
        - xdg-user-dirs-update --set VIDEOS $HOME

    - name: Install dotfiles
      shell: curl -s https://gist.githubusercontent.com/samirettali/9f190ac180aecba1872867acc1e9c83b/raw/install.sh | /bin/bash
      args:
        warn: false

    # Folders creation
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /home/{{ username.stdout }}/Wordlists
        - /home/{{ username.stdout }}/Resources
        - /home/{{ username.stdout }}/Tools
        - /home/{{ username.stdout }}/.bin

    - name: Install fzf
      shell: "{{ item }}"
      with_items:
          - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
          - ~/.fzf/install

    # Install additional software from other package managers
    - pip:
        name:
          - aclpwn
          - capstone
          - jedi
          - keystone-engine
          - magic-wormhole
          - neovim
          - pynvim
          - ropper
          - stegcracker
          - stegoveritas
          - unicorn
          - https://github.com/guelfoweb/knock/archive/knock4.zip
        extra_args: --user
        executable: pip3

    - pip:
        name:
          - google_images_download
          - pwntools
          - scapy
        extra_args: --user
        executable: pip2

    - gem:
        state: present
        name: "{{ item }}"
        user_install: yes
      with_items:
        - evil-winrm
        - zsteg

    # Install custom software
    - name: Build GO tools
      args:
        warn: false
      shell: "{{ item }}"
      with_items:
        - go get -u github.com/003random/getJS
        - go get -u github.com/astaxie/bat
        - go get -u github.com/ffuf/ffuf
        - go get -u github.com/haccer/subjack
        - go get -u github.com/hakluke/hakrawler
        - go get -u github.com/michenriksen/aquatone
        - go get -u github.com/tomnomnom/httprobe
        - go get -u github.com/tomnomnom/meg
        - go get -u github.com/tomnomnom/waybackurls
        - cp /home/{{ username.stdout }}/go/bin/* /home/{{ username.stdout }}/.bin

    - name: Install radare plugins
      shell: "{{ item }}"
      with_items:
          - r2pm init
          - r2pm install r2dec

    - name: Install findomain
      get_url:
        url: https://github.com/Edu4rdSHL/findomain/releases/latest/download/findomain-linux
        dest: /home/{{ username.stdout }}/.bin/findomain

    - name: Download Stegsolve
      get_url:
        url: http://www.caesum.com/handbook/Stegsolve.jar
        dest: /home/{{ username.stdout }}/.bin/stegsolve.jar

    - name: Standalone commands
      args:
        warn: false
      shell: "{{ item }}"
      with_items:
        - wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh
        - stegoveritas_install_deps

    - name: Clone wordlists repositores
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Wordlists
      with_items:
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/1N3/IntruderPayloads
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/danielmiessler/RobotsDisallowed
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/danielmiessler/SecLists
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/dustyfresh/dictionaries
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/dwyl/english-words
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/foospidy/payloads
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/fuzzdb-project/fuzzdb
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/jeanphorn/wordlist/
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/minimaxir/big-list-of-naughty-strings
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/napolux/paroleitaliane
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/swisskyrepo/PayloadsAllTheThings
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/xmendez/wfuzz

    - name: Download rockyou
      get_url:
        url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
        dest: /home/{{ username.stdout }}/Wordlists/rockyou.txt

    - name: Clone resources repositories
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Resources
      with_items:
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/DominicBreuker/stego-toolkit
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/EdOverflow/can-i-take-over-xyz
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/JohnHammond/ctf-katana
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/apsdehal/awesome-ctf
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/enaqx/awesome-pentest
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/jivoi/pentest
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/lanjelot/ctfs
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/sehno/Bug-bounty
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/trimstray/the-book-of-secret-knowledge
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/vitalysim/Awesome-Hacking-Resources
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/zardus/ctf-tools

    - name: Clone tools repositories
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Tools
      with_items:
        # Cracking
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Boran/lusas
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Ganapati/RsaCtfTool
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Sjord/jwtcrack
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/bwall/HashPump
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/frdmn/findmyhash
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/psypanda/hashID
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/rebootuser/Hashmash

        # Enumeration
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/0x646e78/linux-credential-harvester
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/AonCyberLabs/Windows-Exploit-Suggester
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/PowerShellMafia/PowerSploit
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/WazeHell/PE-Linux
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/carlospolop/linux-privilege-escalation-awsome-script
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/jondonas/linux-exploit-suggester-2
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/mzet-/linux-exploit-suggester
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/pentestmonkey/unix-privesc-check
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/rebootuser/LinEnum
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/sleventyeleven/linuxprivchecker
        
        # Recognition   
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/nahamsec/lazyrecon

        # Exploitation
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/commixproject/commix

        # Post exploitation
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/0x00-0x00/ShellPop
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/1N3/PrivEsc
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/mossberg/poet

        # File exfiltration
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Arno0x/DNSExfiltrator

        # Git
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Ebryx/GitDump
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/dxa4481/truffleHog
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/michenriksen/gitrob

        # Process monitoring
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/DominicBreuker/pspy

        # RAT
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/n1nj4sec/pupy

        # Information gathering
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/s0md3v/Striker

        # PHP revershe shells
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/epinna/weevely3
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/flozz/p0wny-shell
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/pentestmonkey/php-reverse-shell
        
        # DNS
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Crypt0s/FakeDns

        # Discovery
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/GerbenJavado/LinkFinder
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/maurosoria/dirsearch
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/s0md3v/Arjun
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/subfinder/subfinder

        # Wireless
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/FluxionNetwork/fluxion
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/derv82/wifite2

        # OSINT
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/martinvigo/email2phonenumber
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/thelinuxchoice/userrecon

        # Web
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/D35m0nd142/LFISuite
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/J3wker/anti-CSRF_Token-Bruteforce
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/andresriancho/w3af
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/arthaud/git-dumper
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/blechschmidt/massdns
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/maaaaz/webscreenshot
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/mhaskar/RCEScanner
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/ticarpi/jwt_tool

        # Data exfiltration 
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/sensepost/DET

        # Misc
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/andrew-d/static-binaries
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/j3ssie/Osmedeus
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/lockedbyte/cryptovenom
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/mpowa705/Simple-Backdoor
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/samirettali/ctf-scripts
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/samirettali/web-recon
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/trailofbits/onesixtyone
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/whid-injector/WHID

         # Windows
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/Dhayalanb/windows-php-reverse-shell
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/SecureAuthCorp/impacket
        - /home/{{ username.stdout }}/.bin/clone-or-pull https://github.com/samratashok/nishang
