---
- name: Kali Linux CTF provisioning
  hosts: all
  tasks:
    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        # Base install
        - zsh
        - git
        - curl
        - wget
        - ncdu
        - tmux
        - neovim
        - yarn
        - ack
        - fzf
        - ranger
        - cloc
        - htop
        - apache2
        - tree
        - xclip
        - python-pip
        - python3-pip
        - openvpn

        # CTF and penetration testing software
        # Audio
        - audacity
        - sonic-visualiser

        # Bruteforce
        - bkhive
        - crunch
        - hydra
        - john
        - wordlists

        # Exploiting
        - exploitdb
        - metasploit-framework

        # Forensics
        - binwalk
        - exiftool
        - libguestfs-tools
        - volatility

        # Fuzzing
        - dirbuster
        - wfuzz

        # Information gathering
        - dnsutils
        - whois

        # Miscellaneous
        - burpsuite
        - findmyhash
        - hexedit

        # Networking
        - aircrack
        - fern-wifi-cracker
        - hping3
        - mitmf
        - nmap
        - wireshark

        # Reversing
        - gdb
        - radare2

        # Samba
        - cifs-utils
        - smbclient
        - smbmap

        # Vulnerability assesment
        - nikto
        - sqlmap

        # Web
        - knockpy
        - sublist3r

    # Configure services
    - name: Enable apache
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Enable postgresql
      become: yes
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Initialize msfdb
      become: yes
      shell: "{{ item }}"
      with_items:
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    - name: Python2 pynvim module
      shell: pip2 install pynvim

    - name: Python3 pynvim module
      shell: pip3 install pynvim

    - name: Python3 neovim module
      shell: pip3 install neovim

    - name: Set zsh shell
      become: yes
      user:
          name: vagrant
          shell: /bin/zsh

    - name: Install dotfiles
      shell: curl -Lks https://bit.do/samirdotfiles | /bin/bash
      # warn: false

    # Wordlists repositories
    - name: Create wordlists directory
      file:
        path: /home/vagrant/Wordlists
        state: directory

    - name: Download wordlists
      command: "{{ item }}"
      args:
        chdir: /home/vagrant/Wordlists
      with_items:
        - git clone https://github.com/1N3/IntruderPayload
        - git clone https://github.com/danielmiessler/SecLists
        - git clone https://github.com/dustyfresh/dictionaries
        - wget https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt

    # CTF repositories
    - name: Create Resources directory
      file:
        path: /home/vagrant/Resources
        state: directory

    - name: Clone CTF repositories
      command: "{{ item }}"
      args:
        chdir: /home/vagrant/Resources
      with_items:
        - git clone https://github.com/zardus/ctf-tools
        - git clone https://github.com/apsdehal/awesome-ctf
        - git clone https://github.com/JohnHammond/ctf-katana
        - git clone https://github.com/DominicBreuker/stego-toolkit
        - git clone https://github.com/enaqx/awesome-pentest
        - git clone https://github.com/jivoi/pentest
        - git clone https://github.com/lanjelot/ctfs
        - git clone https://github.com/trimstray/the-book-of-secret-knowledge

    # CTF Tools
    - name: Create Tools directory
      file:
        path: /home/vagrant/Tools
        state: directory

    - name: Clone tools repositories
      command: "{{ item }}"
      args:
        chdir: /home/vagrant/Tools
      with_items:
        # Cracking
        - git clone https://github.com/rebootuser/Hashmash

        # Enumeration
        - git clone https://github.com/rebootuser/LinEnum
        - git clone https://github.com/mzet-/linux-exploit-suggester
        - git clone https://github.com/jondonas/linux-exploit-suggester-2
        - git clone https://github.com/sleventyeleven/linuxprivchecker

        # Exploitation
        - git clone https://github.com/commixproject/commix

        # Post exploitation
        - git clone https://github.com/mossberg/poet
        - git clone https://github.com/1N3/PrivEsc

        # File exfiltration
        - git clone https://github.com/Arno0x/DNSExfiltrator

        # Git
        - git clone https://github.com/dxa4481/truffleHog
        - git clone https://github.com/michenriksen/gitrob

        # Process monitoring
        - git clone https://github.com/DominicBreuker/pspy

        # RAT
        - git clone https://github.com/n1nj4sec/pupy

        # Information gathering
        - git clone https://github.com/s0md3v/Striker

        # PHP revershe shells
        - git clone https://github.com/flozz/p0wny-shell
        - git clone https://github.com/pentestmonkey/php-reverse-shell
        
        # DNS
        - git clone https://github.com/Crypt0s/FakeDns

        # Discovery
        - git clone https://github.com/maurosoria/dirsearch

        # Wireless
        - git clone https://github.com/FluxionNetwork/fluxion
        - git clone https://github.com/derv82/wifite2

        # Web
        - git clone https://github.com/maaaaz/webscreenshot

    # Install CTF tools
    - name: Install PEDA
      command: "{{ item }}"
      args:
        chdir: /home/vagrant/Tools
      with_items:
          - git clone https://github.com/longld/peda.git
          - echo "source ~/Tools/peda/peda.py" >> /home/vagrant/.gdbinit

    - name: Install Stegsolve
      command: "{{ item }}"
      args:
        chdir: /home/vagrant/.local/bin
      with_items:
        - wget http://www.caesum.com/handbook/Stegsolve.jar -O stegsolve.jar
        - chmod +x stegsolve.jar

    - name: Install shellpop
      become: yes
      shell: "{{ item }}"
      with_items:
        - "apt install python-argcomplete -y"
        - "git clone https://github.com/0x00-0x00/ShellPop"
        - "pip2 install -r ShellPop/requirements.txt"
        - "python2 ShellPop/setup.py install"
        - "rm -rf ShellPop"

      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    # CTF pip tools
    - name: Install pwntools
      shell: pip2 install pwntools

    - name: Install scapy
      shell: pip2 install scapy

    - name: Install stegcracker
      shell: pip3 install stegcracker

    - name: Install magic-wormhole
      shell: pip3 install magic-wormhole

    # Misc pip tools
    - name: Install magic-wormhole
      shell: pip3 install magic-wormhole

