---
- name: Kali Linux CTF provisioning
  hosts: all
  tasks:
    - name: Update repositories
	  become: yes
	  apt:
		update_cache: yes

    - name: Update all packages to the latest version
        apt:
		  upgrade: dist

    - name: Install packages
	  become: true
	  apt:
		name: "{{ packages }}"
	  vars:
		packages:
        # Base install
		- foo
		- zsh
		- git
        - curl
        - wget
        - ncdu
        - tmux
        - neovim
        - yarn
        - fzf
        - ranger
        - cloc
        - htop

        # CTF software
        - dirbuster
		- audacity
		- exiftool
		- sonic-visualizer
        - sqlmap
        - wireshark
        - metasploit-framework
        - john
        - hydra
        - aircrack-ng
        - nikto
        - wordlists 

	# CTF repositories
    - name: Create Resources directory
      file:
        path: Resources
        state: directory

	- name: Clone CTF repositories
      command: "{{ item }}"
      args:
        chdir: Resources/
      with_items:
	    - git clone https://github.com/zardus/ctf-tools
        - git clone https://github.com/apsdehal/awesome-ctf
        - git clone https://github.com/JohnHammond/ctf-katana
        - git clone https://github.com/DominicBreuker/stego-toolkit
        - git clone https://github.com/enaqx/awesome-pentest
        - git clone https://github.com/jivoi/pentest

	# CTF Tools
    - name: Create Tools directory
      file:
        path: Tools
        state: directory

	- name: Clone tools
      command: "{{ item }}"
      args:
        chdir: Tools/
      with_items:
		# Cracking
        - git clone https://github.com/rebootuser/Hashmash

		# Enumeration
      	- git clone https://github.com/rebootuser/LinEnum
		- git clone https://github.com/mzet-/linux-exploit-suggester
		- git clone https://github.com/jondonas/linux-exploit-suggester-2

		# Exploitation
	    - git clone https://github.com/commixproject/commix

        # Post exploitation
        - git clone https://github.com/mossberg/poet

		# File exfiltration
		- git clone https://github.com/Arno0x/DNSExfiltrator

        # Git
        - git clone https://github.com/dxa4481/truffleHog
        - git clone https://github.com/michenriksen/gitrob

        # Process monitoring
        - git clone https://github.com/DominicBreuker/pspy

        # RAT
        - git clone https://github.com/n1nj4sec/pupy

        # Information gathering
        - git clone https://github.com/s0md3v/Striker

        # PHP revershe shells
        - git clone https://github.com/flozz/p0wny-shell
        - git clone https://github.com/pentestmonkey/php-reverse-shell

    - name: Install PEDA
      command: "{{ item }}"
      with_items:
          - git clone https://github.com/longld/peda.git ~/Tools/peda
          - echo "source ~/Tools/peda/peda.py" >> ~/.gdbinit

    # Configure services
    - name: Apache2
	  become: yes
      service:
        name: apache2
        state: started

    - name: Postgresql
	  become: yes
      service:
        name: postgresql
        state: started

    - name: Initialize msfdb
	  become: yes
      shell: "{{ item }}"
      with_items:
        - "systemctl enable postgresql"
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false
