---
- name: Kali Linux CTF provisioning
  hosts: all

  vars_prompt:
    - name: hostname
      prompt: "Hostname for this machine"

    - name: user_password
      prompt: "User password for this machine"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes

    - name: password
      prompt: "Root password for this machine"
      private: yes
      encrypt: "sha512_crypt"
      confirm: yes

  tasks:
    - name: Get current username
      local_action: command whoami
      register: username

    - debug: var=username

    - name: Change user password
      become: yes
      user:
        name: {{ username.stdout }}
        password: "{{ user_password }}"

    - name: Change root password
      become: yes
      user:
        name: root
        password: "{{ password }}"

    - name: Disable automatic repositories update
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Update-Package-Lists "1";'
        replace: 'APT::Periodic::Update-Package-Lists "0";/'

    - name: Disable automatic software update
      replace:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        regexp: 'APT::Periodic::Unattended-Upgrade "1";'
        replace: 'APT::Periodic::Unattended-Upgrade "0";'

    - name: Wait for any possibly running unattended upgrade to finish
      become: yes
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        # Base install
        - ack
        - apache2
        - chromium
        - cloc
        - curl
        - dhex
        - entr
        - fd-find
        - fzf
        - git
        - golang
        - htop
        - imagemagick
        - libapache2-mod-php
        - ncdu
        - neovim
        - nodejs
        - npm
        - openvpn
        - pastebinit
        - php
        - python-pip
        - python3-pip
        - ranger
        - ruby
        - tmux
        - tree
        - wget
        - xclip
        - yarn
        - zsh

        # Docker
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common

        # Binary exploitation
        - checksec

        # Bruteforce
        - bkhive
        - crackmapexec
        - crunch
        - fcrackzip
        - hydra
        - john
        - wordlists

        # Exploiting
        - exploitdb
        - metasploit-framework

        # Forensics
        - audacity
        - sonic-visualiser
        - binwalk
        - exiftool
        - foremost
        - libguestfs-tools
        - qsstv
        - volatility
        - pngcheck
        - steghide
        - zbar-tools

        # Fuzzing and discovery
        - dirbuster
        - gobuster
        - wfuzz
        - sublist3r

        # Information gathering
        - dnsutils
        - whois

        # Web tools
        - eyewitness
        - burpsuite
        - sqlmap
        - knockpy
        - whatweb
        - amass

        # Miscellaneous
        - hexedit
        - gridsite-clients      # url encoding/decoding

        # Networking
        - aircrack-ng
        - dnschef
        - dsniff
        - fern-wifi-cracker
        - hping3
        - ncat
        - netcat
        - nmap
        - tshark
        - wireshark

        # Reversing
        - gdb
        - radare2
        - strace
        - ltrace
        - dex2jar

        # Samba
        - cifs-utils
        - smbclient
        - smbmap

        # Vulnerability analysis
        - golismero
        - lynis
        - nikto

        # Dependencies
        - libzip-dev            # for radare decompiler plugin
        - build-essential       # bitwise
        - libncurses5-dev       # bitwise
        - libreadline-dev       # bitwise
        - libcunit1-dev         # bitwise

    # Docker installation
    - name: Add Docker's GPG key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker's repository
      become: yes
      shell: echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-compose

    - name: Enable Docker
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user to Docker group
      become: yes
      shell: usermod -a -G docker {{ username.stdout }}

    # Configure services for metasploit
    - name: Enable apache
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Enable postgresql
      become: yes
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Initialize msfdb
      become: yes
      shell: "{{ item }}"
      with_items:
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    # Linux stuff
    - name: Set zsh shell
      become: yes
      user:
        name: "{{ username.stdout }}"
        shell: /bin/zsh

    - name: Change XDG directories
      shell: "{{ item }}"
      with_items:
        - xdg-user-dirs-update --set DESKTOP $HOME
        - xdg-user-dirs-update --set DOCUMENTS $HOME
        - xdg-user-dirs-update --set DOWNLOAD $HOME
        - xdg-user-dirs-update --set MUSIC $HOME
        - xdg-user-dirs-update --set PICTURES $HOME
        - xdg-user-dirs-update --set PUBLICSHARE $HOME
        - xdg-user-dirs-update --set TEMPLATES $HOME
        - xdg-user-dirs-update --set VIDEOS $HOME

    - name: Install dotfiles
      shell: curl -s https://gist.githubusercontent.com/samirettali/9f190ac180aecba1872867acc1e9c83b/raw/install.sh | /bin/bash
      args:
        warn: false

    # Folders creation
    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        mode: 0755
      with_items:
        - /home/{{ username.stdout }}/Wordlists
        - /home/{{ username.stdout }}/Resources
        - /home/{{ username.stdout }}/Tools
        - /home/{{ username.stdout }}/.bin

    - name: Clone wordlists repositores
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Wordlists
      with_items:
        - git clone https://github.com/1N3/IntruderPayloads
        - git clone https://github.com/danielmiessler/RobotsDisallowed.git
        - git clone https://github.com/danielmiessler/SecLists.git
        - git clone https://github.com/dustyfresh/dictionaries
        - git clone https://github.com/dwyl/english-words
        - git clone https://github.com/foospidy/payloads.git
        - git clone https://github.com/fuzzdb-project/fuzzdb.git
        - git clone https://github.com/jeanphorn/wordlist/
        - git clone https://github.com/minimaxir/big-list-of-naughty-strings.git
        - git clone https://github.com/swisskyrepo/PayloadsAllTheThings.git
        - git clone https://github.com/xmendez/wfuzz.git

    - name: Download rockyou
      get_url:
        url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
        dest: /home/{{ username.stdout }}/Wordlists/rockyou.txt

    - name: Clone resources repositories
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Resources
      with_items:
        - git clone https://github.com/zardus/ctf-tools
        - git clone https://github.com/apsdehal/awesome-ctf
        - git clone https://github.com/JohnHammond/ctf-katana
        - git clone https://github.com/DominicBreuker/stego-toolkit
        - git clone https://github.com/enaqx/awesome-pentest
        - git clone https://github.com/jivoi/pentest
        - git clone https://github.com/vitalysim/Awesome-Hacking-Resources
        - git clone https://github.com/lanjelot/ctfs
        - git clone https://github.com/trimstray/the-book-of-secret-knowledge
        - git clone https://github.com/EdOverflow/can-i-take-over-xyz

    - name: Clone tools repositories
      shell: "{{ item }}"
      args:
        chdir: /home/{{ username.stdout }}/Tools
      with_items:
        # Cracking
        - git clone https://github.com/rebootuser/Hashmash
        - git clone https://github.com/bwall/HashPump
        - git clone https://github.com/Talanor/findmyhash
        - git clone https://github.com/Ganapati/RsaCtfTool
        - git clone https://github.com/Sjord/jwtcrack
        - git clone https://github.com/psypanda/hashID
        - git clone https://github.com/Boran/lusas

        # Enumeration
        - git clone https://github.com/rebootuser/LinEnum
        - git clone https://github.com/mzet-/linux-exploit-suggester
        - git clone https://github.com/jondonas/linux-exploit-suggester-2
        - git clone https://github.com/sleventyeleven/linuxprivchecker
        - git clone https://github.com/pentestmonkey/unix-privesc-check
        - git clone https://github.com/0x646e78/linux-credential-harvester
        - git clone https://github.com/WazeHell/PE-Linux
        - git clone https://github.com/carlospolop/linux-privilege-escalation-awsome-script
        
        # Recognition   
        - git clone https://github.com/nahamsec/lazyrecon

        # Exploitation
        - git clone https://github.com/commixproject/commix

        # Post exploitation
        - git clone https://github.com/mossberg/poet
        - git clone https://github.com/1N3/PrivEsc
        - git clone https://github.com/0x00-0x00/ShellPop

        # File exfiltration
        - git clone https://github.com/Arno0x/DNSExfiltrator

        # Git
        - git clone https://github.com/dxa4481/truffleHog
        - git clone https://github.com/michenriksen/gitrob

        # Process monitoring
        - git clone https://github.com/DominicBreuker/pspy

        # RAT
        - git clone https://github.com/n1nj4sec/pupy

        # Information gathering
        - git clone https://github.com/s0md3v/Striker

        # PHP revershe shells
        - git clone https://github.com/flozz/p0wny-shell
        - git clone https://github.com/pentestmonkey/php-reverse-shell
        - git clone https://github.com/epinna/weevely3
        
        # DNS
        - git clone https://github.com/Crypt0s/FakeDns

        # Discovery
        - git clone https://github.com/maurosoria/dirsearch
        - git clone https://github.com/s0md3v/Arjun
        - git clone https://github.com/subfinder/subfinder
        - git clone https://github.com/GerbenJavado/LinkFinder

        # Wireless
        - git clone https://github.com/FluxionNetwork/fluxion
        - git clone https://github.com/derv82/wifite2

        # OSINT
        - git clone https://github.com/martinvigo/email2phonenumber

        # Web
        - git clone https://github.com/maaaaz/webscreenshot
        - git clone https://github.com/ticarpi/jwt_tool
        - git clone https://github.com/blechschmidt/massdns

        # Data exfiltration 
        - git clone https://github.com/sensepost/DET

        # Misc
        - git clone https://github.com/andrew-d/static-binaries
        - git clone https://github.com/j3ssie/Osmedeus
        - git clone https://github.com/mpowa705/Simple-Backdoor
        - git clone https://github.com/lockedbyte/cryptovenom
        - git clone https://github.com/Ebryx/GitDump
        - git clone https://github.com/whid-injector/WHID

         # Windows
        - git clone https://github.com/SecureAuthCorp/impacket
        - git clone https://github.com/samratashok/nishang

    # FZF
    # - name: Install fzf
    #   shell: "{{ item }}"
    #   with_items:
    #       - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    #       - ~/.fzf/install

    # Vim plugins
    - name: Download vim plugins
      shell: nvim +PlugUpdate +PlugUpgrade +UpdateRemotePlugins +exit +exit +exit

    # Install additional software from other package managers
    - pip:
        name:
          - pynvim
          - neovim
          - stegcracker
          - magic-wormhole
          - aclpwn
          - stegoveritas
        extra_args: --user
        executable: pip3

    - pip:
        name:
          - pwntools
          - scapy
        extra_args: --user
        executable: pip2

    - gem:
        state: present
        name: "{{ item }}"
        user_install: yes
      with_items:
        - aquatone
        - evil-winrm
        - zsteg

    # Install custom software
    - name: Build GO tools
      shell: "{{ item }}"
      with_items:
        - go get -u github.com/tomnomnom/httprobe
        - go get github.com/003random/getJS
        - go get github.com/astaxie/bat
        - go get github.com/ffuf/ffuf
        - go get github.com/haccer/subjack
        - go get github.com/tomnomnom/meg
        - go get github.com/tomnomnom/waybackurls
        - cp /home/{{ username.stdout }}/go/bin/* /home/{{ username.stdout }}/.bin

    - name: Install radare plugins
      shell: "{{ item }}"
      with_items:
          - r2pm init
          - r2pm install r2dec

    - name: Install findomain
      get_url:
        url: https://github.com/Edu4rdSHL/findomain/releases/latest/download/findomain-linux
        dest: /home/{{ username.stdout }}/.bin/findomain

    - name: Download Stegsolve
      get_url:
        url: http://www.caesum.com/handbook/Stegsolve.jar
        dest: /home/{{ username.stdout }}/.bin/stegsolve.jar

    - name: Standalone commands
      shell: "{{ item }}"
      with_items:
        - wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh
        # - stegoveritas_install_deps
