---
- name: Kali Linux CTF provisioning
  hosts: all
  tasks:
    - name: Wait for any possibly running unattended upgrade to finish
      become: yes
      raw: systemd-run --property="After=apt-daily.service apt-daily-upgrade.service" --wait /bin/true

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        # Base install
        - ack
        - apache2
        - chromium
        - cloc
        - curl
        - dhex
        - entr
        - fd-find
        - fzf
        - git
        - golang
        - htop
        - imagemagick
        - libapache2-mod-php
        - ncdu
        - neovim
        - openvpn
        - php
        - python-pip
        - python3-pip
        - ranger
        - tmux
        - tree
        - wget
        - xclip
        - yarn
        - zsh

        # Docker
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common


        # CTF and penetration testing software

        # Audio
        - audacity
        - sonic-visualiser

        # Binary exploitation
        - checksec

        # Bruteforce
        - bkhive
        - crunch
        - fcrackzip
        - hydra
        - john
        - wordlists

        # Exploiting
        - exploitdb
        - metasploit-framework

        # Forensics
        - binwalk
        - exiftool
        - foremost
        - libguestfs-tools
        - qsstv
        - volatility

        # Fuzzing
        - dirbuster
        - gobuster
        - wfuzz

        # Information gathering
        - dnsutils
        - eyewitness
        - whois

        # Miscellaneous
        - burpsuite
        - hexedit

        # Networking
        - aircrack-ng
        - dnschef
        - dsniff
        - fern-wifi-cracker
        - hping3
        # - mitmf
        - ncat
        - netcat
        - nmap
        - tshark
        - wireshark

        # Reversing
        - gdb
        - radare2
        - strace

        # Samba
        - cifs-utils
        - smbclient
        - smbmap

        # Steganography
        - pngcheck
        - steghide
        - zbar-tools

        # Vulnerability assesment
        - nikto
        - sqlmap

        # Web
        - knockpy
        - sublist3r
        - whatweb

        # Dependencies
        - libzip-dev            # for radare decompiler plugin
        - build-essential       # bitwise
        - libncurses5-dev       # bitwise
        - libreadline-dev       # bitwise
        - libcunit1-dev         # bitwise

    - name: Add Docker's GPG key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker's repository
      become: yes
      shell: echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-compose

    - name: Install bitwise
      shell: "{{ item }}"
      become: yes
      with_items:
          - https://github.com/mellowcandle/bitwise/releases/latest
          - tar xfz bitwise*.tar.gz
          - cd bitwise*
          - ./configure
          - make
          - make install
          - cd ..
          - rm -rf bitwise*

    - name: Remove orphan packages
      apt:
       autoremove: yes

    - name: Enable Docker
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user do Docker group
      become: yes
      shell: usermod -a -G docker vagrant

    # Configure services
    - name: Enable apache
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Enable postgresql
      become: yes
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Initialize msfdb
      become: yes
      shell: "{{ item }}"
      with_items:
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    - name: Python2 pynvim module
      shell: pip2 install pynvim

    - name: Python3 pynvim module
      shell: pip3 install pynvim

    - name: Python3 neovim module
      shell: pip3 install neovim

    - name: Set zsh shell
      become: yes
      user:
        name: vagrant
        shell: /bin/zsh

    - name: Install dotfiles
      shell: curl https://gist.githubusercontent.com/samirettali/9f190ac180aecba1872867acc1e9c83b/raw/install.sh | /bin/bash
      args:
        warn: false

    # Wordlists repositories
    - name: Create wordlists directory
      file:
        path: /home/vagrant/Wordlists
        state: directory

    - name: Download wordlists
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Wordlists
      with_items:
        - git clone https://github.com/1N3/IntruderPayloads
        - ./IntruderPayloads/install.sh
        - git clone https://github.com/jeanphorn/wordlist/
        - git clone https://github.com/dustyfresh/dictionaries
        - git clone https://github.com/dwyl/english-words

    - name: Download rockyou
      get_url:
        url: https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt
        dest: /home/vagrant/Wordlists/rockyou.txt

    # CTF repositories
    - name: Create Resources directory
      file:
        path: /home/vagrant/Resources
        state: directory

    - name: Clone CTF repositories
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Resources
      with_items:
        - git clone https://github.com/zardus/ctf-tools
        - git clone https://github.com/apsdehal/awesome-ctf
        - git clone https://github.com/JohnHammond/ctf-katana
        - git clone https://github.com/DominicBreuker/stego-toolkit
        - git clone https://github.com/enaqx/awesome-pentest
        - git clone https://github.com/jivoi/pentest
        - git clone https://github.com/vitalysim/Awesome-Hacking-Resources
        - git clone https://github.com/lanjelot/ctfs
        - git clone https://github.com/trimstray/the-book-of-secret-knowledge
        - git clone https://github.com/EdOverflow/can-i-take-over-xyz

    # CTF Tools
    - name: Create Tools directory
      file:
        path: /home/vagrant/Tools
        state: directory

    - name: Download linux-local-enum
      get_url:
        url: https://highon.coffee/downloads/linux-local-enum.sh
        dest: /home/vagrant/Tools/linux-local-enum.txt

    - name: Clone tools repositories
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Tools
      with_items:
        # Cracking
        - git clone https://github.com/rebootuser/Hashmash
        - git clone https://github.com/bwall/HashPump
        - git clone https://github.com/Talanor/findmyhash
        - git clone https://github.com/Ganapati/RsaCtfTool

        # Enumeration
        - git clone https://github.com/rebootuser/LinEnum
        - git clone https://github.com/mzet-/linux-exploit-suggester
        - git clone https://github.com/jondonas/linux-exploit-suggester-2
        - git clone https://github.com/sleventyeleven/linuxprivchecker
        - git clone https://github.com/pentestmonkey/unix-privesc-check
        - git clone https://github.com/0x646e78/linux-credential-harvester
        - git clone https://github.com/WazeHell/PE-Linux
        
        # Recognition   
        - git clone https://github.com/nahamsec/lazyrecon

        # Exploitation
        - git clone https://github.com/commixproject/commix

        # Post exploitation
        - git clone https://github.com/mossberg/poet
        - git clone https://github.com/1N3/PrivEsc

        # File exfiltration
        - git clone https://github.com/Arno0x/DNSExfiltrator

        # Git
        - git clone https://github.com/dxa4481/truffleHog
        - git clone https://github.com/michenriksen/gitrob

        # Process monitoring
        - git clone https://github.com/DominicBreuker/pspy

        # RAT
        - git clone https://github.com/n1nj4sec/pupy

        # Information gathering
        - git clone https://github.com/s0md3v/Striker

        # PHP revershe shells
        - git clone https://github.com/flozz/p0wny-shell
        - git clone https://github.com/pentestmonkey/php-reverse-shell
        - git clone https://github.com/epinna/weevely3
        
        # DNS
        - git clone https://github.com/Crypt0s/FakeDns

        # Discovery
        - git clone https://github.com/maurosoria/dirsearch
        - git clone https://github.com/s0md3v/Arjun
        - git clone https://github.com/subfinder/subfinder

        # Wireless
        - git clone https://github.com/FluxionNetwork/fluxion
        - git clone https://github.com/derv82/wifite2

        # OSINT
        - git clone https://github.com/martinvigo/email2phonenumber

        # Web
        - git clone https://github.com/maaaaz/webscreenshot
        - git clone https://github.com/michenriksen/aquatone
        - git clone https://github.com/ticarpi/jwt_tool
        - git clone https://github.com/GerbenJavado/LinkFinder
        - git clone https://github.com/blechschmidt/massdns

        # Data exfiltration 
        - git clone https://github.com/sensepost/DET

        # Misc
        - git clone https://github.com/andrew-d/static-binaries
        - git clone https://github.com/j3ssie/Osmedeus
        - git clone https://github.com/mpowa705/Simple-Backdoor

    # Install CTF tools
    - name: Install GEF
      shell: wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh

    - name: Create .bin directory
      file:
        path: /home/vagrant/.bin
        state: directory

    - name: Download Stegsolve
      get_url:
        url: http://www.caesum.com/handbook/Stegsolve.jar
        dest: /home/vagrant/.bin/stegsolve.jar

    - name: Install stegoVeritas
      become: yes
      shell: "{{ item }}"
      with_items:
        - pip3 install stegoveritas
        - stegoveritas_install_deps

    - name: Install zsteg
      shell: gem install --user zsteg

    - name: Install shellpop
      become: yes
      shell: "{{ item }}"
      with_items:
        - apt install python-argcomplete -y
        - git clone https://github.com/0x00-0x00/ShellPop
        - pip2 install -r ShellPop/requirements.txt
        - python2 ShellPop/setup.py install
        - rm -rf ShellPop

    # CTF pip tools
    - name: Install pwntools
      shell: pip3 install pwntools

    - name: Install scapy
      shell: pip2 install scapy

    - name: Install stegcracker
      shell: pip3 install stegcracker

    # Misc pip tools
    - name: Install magic-wormhole
      shell: pip3 install magic-wormhole

    # FZF
    - name: Install fzf
      shell: "{{ item }}"
      with_items:
          - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
          - ~/.fzf/install

    # Vim plugins
    - name: Download vim plugins
      shell: nvim +PlugUpdate +PlugUpgrade +UpdateRemotePlugins +exit +exit +exit

    # Change XDG directories
    - name: Change XDG directories
      shell: "{{ item }}"
      with_items:
        - xdg-user-dirs-update --set DESKTOP $HOME
        - xdg-user-dirs-update --set DOCUMENTS $HOME
        - xdg-user-dirs-update --set DOWNLOAD $HOME
        - xdg-user-dirs-update --set MUSIC $HOME
        - xdg-user-dirs-update --set PICTURES $HOME
        - xdg-user-dirs-update --set PUBLICSHARE $HOME
        - xdg-user-dirs-update --set TEMPLATES $HOME
        - xdg-user-dirs-update --set VIDEOS $HOME

    # Install radare plugins 
    - name: Install radare plugins
      shell: "{{ item }}"
      with_items:
          - r2pm init
          - r2pm install r2dec

    - name: Install ffuf
      shell: "{{ item }}"
      with_items:
        - go get github.com/ffuf/ffuf
        - sudo cp $HOME/go/bin/ffuf /bin

    - name: Install aquatone
      shell: "{{ item }}"
      with_items:
        - git clone https://github.com/michenriksen/aquatone
        - cd aquatone
        - ./build.sh
        - cd build
        - unzip aquatone_linux_amd64_*.zip
        - sudo cp aquatone /bin

    - name: Install httprobe
      shell: "{{ item }}"
      with_items:
        - go get -u github.com/tomnomnom/httprobe
        - sudo cp $HOME/go/bin/httprobe /bin


    - name: Install subjack
      shell: "{{ item }}"
      with_items:
        - go get github.com/haccer/subjack
        - sudo cp $HOME/go/bin/subjack /bin

    - name: Install waybackurls
      shell: "{{ item }}"
      with_items:
        - go get github.com/tomnomnom/waybackurls
        - sudo cp $HOME/go/bin/waybackurls /bin

    - name: Install bat
      shell: "{{ item }}"
      with_items:
        - go get github.com/astaxie/bat
        - sudo cp $HOME/go/bin/bat /bin

    - name: Install meg
      shell: "{{ item }}"
      with_items:
        - go get github.com/tomnomnom/meg
        - sudo cp $HOME/go/bin/meg /bin

    - name: Install getjs
      shell: "{{ item }}"
      with_items:
        - go get github.com/003random/getJS
        - sudo cp $HOME/go/bin/getJS /bin

    - name: Install findomain
      shell: "{{ item }}"
      with_items:
        - wget https://github.com/Edu4rdSHL/findomain/releases/latest/download/findomain-linux
        - chmod +x findomain-linux
        - sudo mv findomain-linux /bin
