---
- name: Kali Linux CTF provisioning
  hosts: all
  tasks:
    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Upgrade packages
      become: yes
      apt:
        upgrade: dist

    - name: Install packages
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        # Base install
        - zsh
        - git
        - curl
        - wget
        - ncdu
        - tmux
        - neovim
        - yarn
        - ack
        - fzf
        - ranger
        - cloc
        - htop
        - apache2
        - php
        - libapache2-mod-php
        - tree
        - xclip
        - python-pip
        - python3-pip
        - openvpn
        - imagemagick

        # Docker
        - apt-transport-https
        - ca-certificates
        - gnupg-agent
        - software-properties-common


        # CTF and penetration testing software
        # Audio
        - audacity
        - sonic-visualiser

        # Binary exploitation
        - checksec

        # Bruteforce
        - bkhive
        - crunch
        - hydra
        - john
        - wordlists
        - fcrackzip

        # Exploiting
        - exploitdb
        - metasploit-framework

        # Forensics
        - binwalk
        - exiftool
        - foremost
        # - libguestfs-tools
        - volatility

        # Fuzzing
        - dirbuster
        - gobuster
        - wfuzz

        # Information gathering
        - dnsutils
        - whois

        # Miscellaneous
        - burpsuite
        - findmyhash
        - hexedit

        # Networking
        - aircrack-ng
        - dnschef
        - dsniff
        - fern-wifi-cracker
        - hping3
        - mitmf
        - netcat
        - ncat
        - nmap
        - wireshark
        - tshark

        # Reversing
        - gdb
        - radare2
        - strace

        # Samba
        - cifs-utils
        - smbclient
        - smbmap

        # Steganography
        - pngcheck
        - steghide
        - zbar-tools

        # Vulnerability assesment
        - nikto
        - sqlmap

        # Web
        - knockpy
        - sublist3r
        - whatweb

        # Dependencies
        - libzip-dev            # for radare decompiler plugin

    - name: Add Docker's GPG key
      become: yes
      shell: curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add -

    - name: Add Docker's repository
      become: yes
      shell: echo 'deb [arch=amd64] https://download.docker.com/linux/debian buster stable' > /etc/apt/sources.list.d/docker.list

    - name: Update repositories
      become: yes
      apt:
        update_cache: yes

    - name: Install Docker
      become: yes
      apt:
        name: "{{ packages }}"
      vars:
        packages:
        - docker-ce
        - docker-compose

    - name: Enable Docker
      become: yes
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Add user do Docker group
      become: yes
      shell: usermod -a -G docker vagrant

    # Configure services
    - name: Enable apache
      become: yes
      systemd:
        name: apache2
        state: started
        enabled: yes

    - name: Enable postgresql
      become: yes
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Initialize msfdb
      become: yes
      shell: "{{ item }}"
      with_items:
        - "msfdb init"
        - "touch /usr/share/metasploit-framework/.initialized"
      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    - name: Python2 pynvim module
      shell: pip2 install pynvim

    - name: Python3 pynvim module
      shell: pip3 install pynvim

    - name: Python3 neovim module
      shell: pip3 install neovim

    - name: Set zsh shell
      become: yes
      user:
        name: vagrant
        shell: /bin/zsh

    - name: Install dotfiles
      shell: curl -Lks https://bit.do/samirdotfiles | /bin/bash
      args:
        warn: false

    # Wordlists repositories
    - name: Create wordlists directory
      file:
        path: /home/vagrant/Wordlists
        state: directory

    - name: Download wordlists
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Wordlists
      with_items:
        - git clone https://github.com/1N3/IntruderPayloads
        - ./IntruderPayloads/install.sh
        - git clone https://github.com/jeanphorn/wordlist/
        - git clone https://github.com/dustyfresh/dictionaries
        - git clone https://github.com/dwyl/english-words
        - wget https://github.com/brannondorsey/naive-hashcat/releases/download/data/rockyou.txt

    # CTF repositories
    - name: Create Resources directory
      file:
        path: /home/vagrant/Resources
        state: directory

    - name: Clone CTF repositories
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Resources
      with_items:
        - git clone https://github.com/zardus/ctf-tools
        - git clone https://github.com/apsdehal/awesome-ctf
        - git clone https://github.com/JohnHammond/ctf-katana
        - git clone https://github.com/DominicBreuker/stego-toolkit
        - git clone https://github.com/enaqx/awesome-pentest
        - git clone https://github.com/jivoi/pentest
        - git clone https://github.com/lanjelot/ctfs
        - git clone https://github.com/trimstray/the-book-of-secret-knowledge
        - git clone https://github.com/zed-0xff/zsteg

    # CTF Tools
    - name: Create Tools directory
      file:
        path: /home/vagrant/Tools
        state: directory

    - name: Clone tools repositories
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/Tools
      with_items:
        # Cracking
        - git clone https://github.com/rebootuser/Hashmash
        - git clone https://github.com/bwall/HashPump

        # Enumeration
        - git clone https://github.com/rebootuser/LinEnum
        - git clone https://github.com/mzet-/linux-exploit-suggester
        - git clone https://github.com/jondonas/linux-exploit-suggester-2
        - git clone https://github.com/sleventyeleven/linuxprivchecker
        - git clone https://github.com/pentestmonkey/unix-privesc-check
        - git clone https://github.com/0x646e78/linux-credential-harvester
        - git clone https://github.com/WazeHell/PE-Linux
        - wget https://highon.coffee/downloads/linux-local-enum.sh
        
        # Recognition   
        - git clone https://github.com/nahamsec/lazyrecon

        # Exploitation
        - git clone https://github.com/commixproject/commix

        # Post exploitation
        - git clone https://github.com/mossberg/poet
        - git clone https://github.com/1N3/PrivEsc

        # File exfiltration
        - git clone https://github.com/Arno0x/DNSExfiltrator

        # Git
        - git clone https://github.com/dxa4481/truffleHog
        - git clone https://github.com/michenriksen/gitrob

        # Process monitoring
        - git clone https://github.com/DominicBreuker/pspy

        # RAT
        - git clone https://github.com/n1nj4sec/pupy

        # Information gathering
        - git clone https://github.com/s0md3v/Striker

        # PHP revershe shells
        - git clone https://github.com/flozz/p0wny-shell
        - git clone https://github.com/pentestmonkey/php-reverse-shell
        - git clone https://github.com/epinna/weevely3
        
        # DNS
        - git clone https://github.com/Crypt0s/FakeDns

        # Discovery
        - git clone https://github.com/maurosoria/dirsearch
        - git clone https://github.com/s0md3v/Arjun
        - git clone https://github.com/subfinder/subfinder

        # Wireless
        - git clone https://github.com/FluxionNetwork/fluxion
        - git clone https://github.com/derv82/wifite2

        # OSINT
        - git clone https://github.com/martinvigo/email2phonenumber

        # Web
        - git clone https://github.com/maaaaz/webscreenshot
        - git clone https://github.com/michenriksen/aquatone

        # Data exfiltration 
        - git clone https://github.com/sensepost/DET

        # Misc
        - git clone https://github.com/andrew-d/static-binaries
        - git clone https://github.com/j3ssie/Osmedeus
        - git clone https://github.com/mpowa705/Simple-Backdoor

    # Install CTF tools
    - name: Install GEF
      shell: wget -q -O- https://github.com/hugsy/gef/raw/master/scripts/gef.sh | sh

    - name: Install Stegsolve
      shell: "{{ item }}"
      args:
        chdir: /home/vagrant/.local/bin
      with_items:
        - wget http://www.caesum.com/handbook/Stegsolve.jar -O stegsolve.jar
        - chmod +x stegsolve.jar

    - name: Install stegoVeritas
      become: yes
      shell: "{{ item }}"
      with_items:
        - pip3 install stegoveritas
        - stegoveritas_install_deps

    - name: Install zsteg
      become: yes
      shell: gem install --user zsteg

    - name: Install shellpop
      become: yes
      shell: "{{ item }}"
      with_items:
        - apt install python-argcomplete -y
        - git clone https://github.com/0x00-0x00/ShellPop
        - pip2 install -r ShellPop/requirements.txt
        - python2 ShellPop/setup.py install
        - rm -rf ShellPop

      args:
        creates: "/usr/share/metasploit-framework/.initialized"
        warn: false

    # CTF pip tools
    - name: Install pwntools
      shell: pip2 install pwntools

    - name: Install scapy
      shell: pip2 install scapy

    - name: Install stegcracker
      shell: pip3 install stegcracker

    # Misc pip tools
    - name: Install magic-wormhole
      shell: pip3 install magic-wormhole

    # FZF
    - name: Install fzf
      shell: "{{ item }}"
      with_items:
          - git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
          - ~/.fzf/install

    # Vim plugins
    - name: Download vim plugins
      shell: nvim +PlugUpdate +PlugUpgrade +UpdateRemotePlugins +exit +exit +exit

    # Change XDG directories
    - name: Change XDG directories
      shell: "{{ item }}"
      with_items:
        - xdg-user-dirs-update --set DESKTOP $HOME
        - xdg-user-dirs-update --set DOCUMENTS $HOME
        - xdg-user-dirs-update --set DOWNLOAD $HOME
        - xdg-user-dirs-update --set MUSIC $HOME
        - xdg-user-dirs-update --set PICTURES $HOME
        - xdg-user-dirs-update --set PUBLICSHARE $HOME
        - xdg-user-dirs-update --set TEMPLATES $HOME
        - xdg-user-dirs-update --set VIDEOS $HOME

    # Install radare plugins 
    - name: Install radare plugins
      shell: "{{ item }}"
      with_items:
          - r2pm init
          - r2pm install r2dec

    - name: Install ffuf
      shell: go get github.com/ffuf/ffuf
